import Link from "next/link"
import { ArrowLeft } from "lucide-react"

export const metadata = {
  title: "About getChimed",
  description: "Turn NPS feedback into action without losing the nuance.",
}

export default function AboutPage() {
  return (
    <div className="min-h-svh flex flex-col bg-background">
      <div className="flex-1">
        {/* Back button */}
        <div className="border-b border-border px-4 py-4 sm:px-6 lg:px-8">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="size-4" />
            Back to app
          </Link>
        </div>

        {/* Main content */}
        <article className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8 space-y-16">
          {/* Hero section */}
          <section className="space-y-6">
            <h1 className="text-5xl font-bold tracking-tight text-foreground sm:text-6xl text-balance">
              About getChimed
            </h1>
            <p className="text-xl leading-relaxed text-muted-foreground max-w-2xl">
              getChimed turns NPS feedback into action, without losing the nuance in a spreadsheet.
            </p>
          </section>

          {/* The framework */}
          <section className="space-y-4 border-t border-border pt-12">
            <h2 className="text-2xl font-bold text-foreground">The framework</h2>
            <p className="text-base leading-relaxed text-foreground">
              Built on Rahul Vohra's product-market fit framework (Superhuman) — segmenting responses the way his engine does, and asking what promoters love and what passives need, instead of averaging everyone's feedback into one flat number.
            </p>
          </section>

          {/* How it works */}
          <section className="space-y-4 border-t border-border pt-12">
            <h2 className="text-2xl font-bold text-foreground">How it works</h2>
            <p className="text-base leading-relaxed text-foreground">
              Every theme you see is generated by an LLM reading real responses — never keyword-matched, never rewritten. If a comment doesn't clearly fit a theme, it stays visible as unclustered rather than force-fit.
            </p>
          </section>

          {/* About Swabhi */}
          <section className="space-y-4 border-t border-border pt-12">
            <h2 className="text-2xl font-bold text-foreground">Built by Swabhi</h2>
            <p className="text-base leading-relaxed text-foreground">
              Built solo, still evolving. If something looks off, it probably is — tell me. Feedback, bugs, and feature requests are always welcome at{' '}
              <a
                href="mailto:swabhig@gmail.com"
                className="font-medium text-promoter underline-offset-4 hover:underline"
              >
                swabhig@gmail.com
              </a>
              .
            </p>
          </section>

          {/* CTA */}
          <section className="border-t border-border pt-12">
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-base font-medium text-promoter underline-offset-4 hover:underline"
            >
              Start analyzing →
            </Link>
          </section>
        </article>
      </div>
    </div>
  )
}
